### PR TITLE
Tests, shutdown corrections, and memory re-use

### PR DESCRIPTION
**Pull request by sebastiang**
I put in a  set of changes that mostly includes a few tests and some tweaks to ensure that server & client can shut down cleanly even if they haven't done anything.
I corrected what I _think_ are a few correctness errors (see 963dc1d, 3aa2a73)
Secondly, I made send & receive work with ArraySegment<byte>, potentially alleviating the need to copy data into buffers to pass it to clients, who are likely to copy it into whatever buffer they are working with anyway.

### CODE REVIEW

**Comment by 7sharp9** [comment]
Thanks, Ill cherry pick the ones I think will work...

**Comment by sebastiang** [comment]
Cheers! I know it looks like exposing ArraySegment is exposing server resource, but I think they are already exposed. After all, unless the receive function calls its echo argument, the SAEA it's involved with won't be returned anyway. This is a highly cooperative model anyway, so why not let the function right at the array. Anyway, thanks for the consideration!

**Comment by 7sharp9** [comment]
It not just that its issues with heavy load and denial of service. The copy is there to get the buffer back into the pool along with the SAEA to stop a IO worker thread being created if the callback takes to long.  There are plans for a pipeline stage in and out of the TcpServer.  A specialised pipelet will have an ArraySegment based queuing mechanism...

**Comment by 7sharp9** [comment]
I merged what I could into the branch Im working on, this will go into master soon.

**Comment by sebastiang** [comment]
Cheers!

**Pull request closed without merging**
