### PR TITLE
Exchange callbacks for events/observables

### PR DESCRIPTION
**Pull request by panesofglass**
Rather than passing callbacks, expose events for connected, disconnected, received, and sent. These can be consumed as events or as `IObservable<'T>`. See `HttpServer` for an example.

**NOTE: This PR builds upon #33**

### CODE REVIEW

**Comment by panesofglass** [comment]
@colinbull Is any of this going to cause you any angst in [FSharp.Actor](https://github.com/colinbull/FSharp.Actor)? I don't see anything that indicates these changes will be a problem.

**Comment by colinbull** [comment]
I don't think so, currently rewriting the remoting stuff anyway. So I'll just consume the changes. 
Framing and Subscriptions (ala ZeroMQ) are two things I would like too see in Fracture. It would certainly make my life easier.

**Comment by panesofglass** [comment]
@colinbull What do you mean by Framing and Subscriptions? For the latter, do you mean something like Rx or IObservables?

@7sharp9, do you have any thoughts here? You are the brains in this operation.

**Comment by 7sharp9** [comment]
I don't particularly like Rx style so I don't have an opinion there.  

I think Colin meant message framing e.g. how do I send a message that spans more than a single packet.  In this instance I would adopt an existing framing mechanism, or implement something simplistic: `Terminator | Length | Terminator` probably using EOT or similar.

**Comment by colinbull** [comment]
The way by framing I mean [this](http://api.zeromq.org/2-1:zmq-tcp) and there is and example in the C# bindings for zeromq [here](https://github.com/zeromq/clrzmq/tree/master/src/ZeroMQ.SimpleTests). It just simplifies the communication, (send a bunch of frames from the client and then enumerate on the receiver side until you get an ending frame). I guess I could use a protocol that is already framed and maybe fracture is not intended to be opinionated in this way. An example maybe, 

```
//Sender 

 Fracture.send ("tcp://localhost:1234", [Frame("this is my header frame");Frame("this is my message payload")])

//Receiver
let message = 
         Fracture.receive ("tcp://localhsot:1234") 
         |> Seq.fold (fun msg frame -> 
                      msg + frame.Payload
                    ) ""
```

As for subscriptions I mean like a lightweight message queue, i.e. A socket subscriber can listen to an endpoint and based on the topic it is subscribed to choose to consume messages or not. Again in ZeroMQ this is achieved by passing a header frame with that contains the topic in. If the string in that header frame matches the clients subscription then is begins consuming the frames of that message. I was thinking of something like this

```
 use sub = Fracture.subscribe("tcp://localhost:1234", ["xyzTopic"; "myTopic"])
 sub |> Observable.add (fun frames -> /* handle message */) 
```

I'm not sure what the intended scope of fracture is and maybe this should be built on top.  This is just a brain dump really.

**Comment by 7sharp9** [comment]
What performance differences if any did you get from switching to observable?

**Pull request merged**
